name: CI
on:
  push:

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
        always-auth: true
    - run: yarn install
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: yarn test
