# This is a basic workflow to help you get started with Actions

name: test-action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a simple command
    - name: test1
      run: $AzureAppServiceName = $(terraform output app_service_name -no-color)
    - name: test2
      run: Write-Output "App service name is $AzureAppServiceName"






